# Generated by tools/utilities/gen_cmake_sources.py from configure.py and
# config/<version>/splits.txt. Do not edit; re-run the script instead.

set(TP_Z2AUDIOLIB_SOURCES
    Z2Calc.cpp
    Z2AudioArcLoader.cpp
    Z2Param.cpp
    Z2SoundMgr.cpp
    Z2SoundStarter.cpp
    Z2SoundHandles.cpp
    Z2SeMgr.cpp
    Z2SeqMgr.cpp
    Z2StatusMgr.cpp
    Z2SceneMgr.cpp
    Z2FxLineMgr.cpp
    Z2SoundInfo.cpp
    Z2Audience.cpp
    Z2SoundObject.cpp
    Z2SoundObjMgr.cpp
    Z2Creature.cpp
    Z2LinkMgr.cpp
    Z2EnvSeMgr.cpp
    Z2WolfHowlMgr.cpp
    Z2SpeechMgr2.cpp
    Z2AudioMgr.cpp
)
