# Generated by tools/utilities/gen_cmake_sources.py from configure.py and
# config/<version>/splits.txt. Do not edit; re-run the script instead.

set(TP_MACHINE_SOURCES
    m_Do_main.cpp
    m_Do_printf.cpp
    m_Do_audio.cpp
    m_Do_controller_pad.cpp
    m_Do_graphic.cpp
    m_Do_machine.cpp
    m_Do_mtx.cpp
    m_Do_ext.cpp
    m_Do_lib.cpp
    m_Do_Reset.cpp
    m_Do_dvd_thread.cpp
    m_Do_DVDError.cpp
    m_Do_MemCard.cpp
    m_Do_MemCardRWmng.cpp
    m_Do_machine_exception.cpp
)
