# Generated by tools/utilities/gen_cmake_sources.py from configure.py and
# config/<version>/splits.txt. Do not edit; re-run the script instead.

set(TP_C_SOURCES
    c_damagereaction.cpp
    c_dylink.cpp
)
