#!/usr/bin/env python3

###
# Answers: "if every actor REL were linked into one static executable, which
# strong symbols would collide?"
#
# The original game links each actor into its own REL, so two actors may define
# the same non-static global (e.g. `l_HIO`) without conflict. A port that links
# everything statically must make those unique. This script compiles each
# src/d/actor/*.cpp to an object (host compiler, -O0, no Metrowerks headers),
# collects the strong (non-weak) external symbols, and reports duplicates.
#
# Notes:
#   * d_a_npc2.cpp / d_a_npc4.cpp are #included into d_a_npc.cpp and are skipped.
#   * Only actors are checked; DOL-resident TUs are not, so real numbers can be
#     somewhat higher.
#   * Objects that fail to compile (see clang_sweep.py) are simply absent.
#
# Usage (from anywhere):
#   python3 tools/utilities/dup_symbol_check.py
#   python3 tools/utilities/dup_symbol_check.py --report docs/port/duplicate-symbols.md
###

import argparse
import collections
import os
import platform
import re
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INCLUDED_FRAGMENTS = ("d_a_npc2.cpp", "d_a_npc4.cpp")


def compile_one(args, src, outdir):
    obj = os.path.join(outdir, src.replace("/", "_") + ".o")
    cmd = [
        args.cxx, f"-std={args.std}", "-c", "-O0", "-fdeclspec", "-w", "-fno-exceptions",
        f"-DVERSION={args.version}", "-D__GEKKO__",
        "-I", "include", "-I", "src", "-I", "libs/JSystem/include",
        "-I", "libs/dolphin/include", "-I", "libs/dolphin/include/dolphin", "-I", "assets/GZ2E01",
        src, "-o", obj,
    ]
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True)
    return (src, obj if r.returncode == 0 else None)


def strong_symbols(obj):
    """Names of strong external definitions in an object file."""
    syms = []
    if platform.system() == "Darwin":
        out = subprocess.run(["nm", "-m", obj], capture_output=True, text=True).stdout
        for line in out.splitlines():
            if "(undefined)" in line or "weak external" in line or "non-external" in line:
                continue
            if " external " in line:
                name = line.rsplit(" ", 1)[-1]
                syms.append(name[1:] if name.startswith("_") else name)  # Mach-O prepends one underscore
    else:
        out = subprocess.run(["nm", "-g", "--defined-only", obj], capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if len(parts) == 3 and parts[1] in "TDBRS":
                syms.append(parts[2])
    # RTTI/vtables and libc++ inline math are emitted as weak on ELF; Mach-O nm hides that.
    return [s for s in syms if not re.match(r"_?ZT[ISV]|_?ZNSt3__1", s)]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cxx", default="clang++")
    ap.add_argument("--std", default="c++17")
    ap.add_argument("--version", type=int, default=0)
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--report")
    args = ap.parse_args()

    srcs = sorted(
        os.path.relpath(os.path.join(dp, f), ROOT)
        for dp, _, fs in os.walk(ROOT / "src/d/actor")
        for f in fs
        if f.endswith(".cpp") and f not in INCLUDED_FRAGMENTS
    )
    with tempfile.TemporaryDirectory() as tmp:
        print(f"compiling {len(srcs)} actor TUs …", file=sys.stderr)
        with ThreadPoolExecutor(args.jobs) as ex:
            built = list(ex.map(lambda s: compile_one(args, s, tmp), srcs))
        failed = [s for s, o in built if o is None]
        owners = collections.defaultdict(set)
        for s, o in built:
            if o:
                for sym in strong_symbols(o):
                    owners[sym].add(s)

    dups = {k: sorted(v) for k, v in owners.items() if len(v) > 1}

    def demangle(names):
        try:
            out = subprocess.run(["c++filt"], input="\n".join(names), capture_output=True, text=True).stdout.splitlines()
            return dict(zip(names, out)) if len(out) == len(names) else {n: n for n in names}
        except OSError:
            return {n: n for n in names}

    pretty = demangle(list(dups))
    ok = len(srcs) - len(failed)
    lines = [
        "# Duplicate strong symbols across actor TUs (generated)\n",
        "Generated by `python3 tools/utilities/dup_symbol_check.py`. If every actor were linked into a single executable (instead of one REL each), these definitions would collide and need `static` / an anonymous namespace / a single definition.\n",
        f"* Actor TUs compiled to objects: **{ok} of {len(srcs)}** ({len(failed)} failed to compile, so their symbols are not checked; see `compile-sweep.md`).",
        f"* Distinct symbols defined in more than one TU: **{len(dups)}**.\n",
        "| Symbols | Defined in TUs | Example TUs |",
        "|---|---|---|",
    ]
    for sym, fs in sorted(dups.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        ex = ", ".join(f"`{os.path.basename(f)}`" for f in fs[:3]) + (" …" if len(fs) > 3 else "")
        lines.append(f"| `{pretty[sym]}` | {len(fs)} | {ex} |")
    if failed:
        lines.append("\n## Actor TUs that did not compile in this pass\n")
        lines += [f"* `{f}`" for f in failed]
    text = "\n".join(lines) + "\n"
    print("\n".join(lines[:5]))
    if args.report:
        (ROOT / args.report).write_text(text)
        print(f"wrote {args.report}", file=sys.stderr)


if __name__ == "__main__":
    main()
