#!/usr/bin/env python3

###
# Generates the `sources.cmake` files that feed the CMake build.
#
# The authoritative source list for the project is `configure.py` (which
# library each file belongs to) together with `config/<version>/splits.txt`
# and `config/<version>/rels/*/splits.txt` (which translation units actually
# exist in a given game version). This script combines them for the three
# GameCube versions and writes explicit, version-aware source lists next to
# the hand-written CMakeLists.txt files, so CMake never has to glob.
#
# Only game and middleware code is listed. The Dolphin SDK implementation,
# Metrowerks runtime (MSL, Runtime.PPCEABI.H, MetroTRK), the REL loader and the
# debugger stubs are intentionally left out; on a host build they are replaced
# by the platform layer (see docs/port/cmake.md).
#
# Usage (from anywhere):
#   python3 tools/utilities/gen_cmake_sources.py            # (re)write the files
#   python3 tools/utilities/gen_cmake_sources.py --check    # exit 1 if out of date
###

import argparse
import re
import runpy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# GameCube versions, in the order of VERSION_GCN_* in include/global.h.
GCN_VERSIONS = ["GZ2E01", "GZ2P01", "GZ2J01"]

# Where each group of configure.py libraries lives in the CMake tree.
#   (directory, CMake variable, configure.py library names)
# The special name "d_a_*" selects every actor REL library.
GROUPS = [
    ("src/m_Do", "TP_MACHINE_SOURCES", ["machine"]),
    ("src/c", "TP_C_SOURCES", ["c"]),
    ("src", "TP_FRAMEWORK_SOURCES", ["framework"]),
    ("src", "TP_DYNAMICLINK_SOURCES", ["DynamicLink"]),
    ("src", "TP_PROFILE_LIST_SOURCES", ["f_pc_profile_lst"]),
    ("src/d", "TP_DOLZEL_SOURCES", ["dolzel2"]),
    ("src/d/actor", "TP_ACTORS_SOURCES", ["d_a_*"]),
    ("src/SSystem", "TP_SSYSTEM_SOURCES", ["SSystem"]),
    ("src/Z2AudioLib", "TP_Z2AUDIOLIB_SOURCES", ["Z2AudioLib"]),
]

JSYSTEM_DIR = "libs/JSystem"
JSYSTEM_SRC_DIR = "libs/JSystem/src"

HEADER = """\
# Generated by tools/utilities/gen_cmake_sources.py from configure.py and
# config/<version>/splits.txt. Do not edit; re-run the script instead.
"""


def load_libs():
    """Evaluate configure.py without generating a build and return config.libs."""
    sys.path.insert(0, str(ROOT))
    import tools.project as project

    project.generate_build = lambda *a, **k: None
    project.calculate_progress = lambda *a, **k: None
    argv, sys.argv = sys.argv, ["configure.py", "--version", GCN_VERSIONS[0], "--no-progress"]
    try:
        glb = runpy.run_path(str(ROOT / "configure.py"), run_name="__main__")
    finally:
        sys.argv = argv
    return glb["config"].libs


def read_units(splits: Path):
    rx = re.compile(r"^(\S+\.(?:cpp|c|cp|s)):\s*$")
    units = set()
    for line in splits.read_text(encoding="utf-8").splitlines():
        m = rx.match(line)
        if m:
            units.add(m.group(1))
    return units


def units_per_version():
    out = {}
    for ver in GCN_VERSIONS:
        units = read_units(ROOT / "config" / ver / "splits.txt")
        for splits in sorted((ROOT / "config" / ver / "rels").glob("*/splits.txt")):
            units |= read_units(splits)
        out[ver] = units
    return out


def source_path(lib, obj):
    """Repo-relative path of an object's source file, mirroring tools/project.py."""
    name = obj.name
    prefix = lib.get("strip_prefix")
    if prefix and name.startswith(prefix):
        name = name[len(prefix):]
    src_dir = obj.options.get("src_dir") or lib.get("src_dir") or "src"
    return Path(src_dir) / name


def collect(libs, units, lib_names):
    """Return [(repo-relative path, frozenset(versions))] for the given libraries."""
    entries = []
    for lib in libs:
        name = lib["lib"]
        if not any(name == n or (n.endswith("*") and name.startswith(n[:-1])) for n in lib_names):
            continue
        for obj in lib["objects"]:
            versions = frozenset(v for v in GCN_VERSIONS if obj.name in units[v])
            if not versions:
                continue
            path = source_path(lib, obj)
            if not (ROOT / path).is_file():
                sys.exit(f"{obj.name}: source file {path} not found")
            entries.append((path, versions))
    return entries


def rel(path: Path, base: str):
    return path.relative_to(base).as_posix()


def emit_list(var, entries, base):
    """Render one source list; version-specific entries go in guarded appends."""
    common = [rel(p, base) for p, v in entries if len(v) == len(GCN_VERSIONS)]
    lines = [f"set({var}"] + [f"    {p}" for p in common] + [")"]
    partial = {}
    for p, v in entries:
        if len(v) != len(GCN_VERSIONS):
            partial.setdefault(tuple(sorted(v)), []).append(rel(p, base))
    for versions, paths in sorted(partial.items()):
        cond = " OR ".join(f'TP_VERSION STREQUAL "{v}"' for v in versions)
        lines.append(f"if({cond})")
        lines.append(f"    list(APPEND {var}")
        lines += [f"        {p}" for p in paths]
        lines += ["    )", "endif()"]
    return "\n".join(lines) + "\n"


def build_outputs(libs, units):
    outputs = {}

    by_dir = {}
    for directory, var, names in GROUPS:
        entries = collect(libs, units, names)
        by_dir.setdefault(directory, []).append(emit_list(var, entries, directory))
    for directory, chunks in by_dir.items():
        outputs[Path(directory) / "sources.cmake"] = HEADER + "\n" + "\n".join(chunks)

    modules = []
    chunks = []
    for lib in libs:
        if lib.get("src_dir") != JSYSTEM_SRC_DIR:
            continue
        entries = collect(libs, units, [lib["lib"]])
        # The same library name can appear for several SDKs; only JSystem here.
        entries = [(p, v) for p, v in entries if str(p).startswith(JSYSTEM_SRC_DIR + "/")]
        if not entries:
            continue
        modules.append(lib["lib"])
        chunks.append(emit_list(f"TP_JSYSTEM_{lib['lib'].upper()}_SOURCES", entries, JSYSTEM_DIR))
    mods = "set(TP_JSYSTEM_MODULES\n" + "".join(f"    {m}\n" for m in modules) + ")\n"
    outputs[Path(JSYSTEM_DIR) / "sources.cmake"] = HEADER + "\n" + mods + "\n" + "\n".join(chunks)
    return outputs


def sources_for_version(version):
    """Repo-relative paths of every translation unit the CMake build compiles for `version`.

    Same selection as the generated sources.cmake files, so other tools (clang_sweep.py) can
    check exactly the file set that the build uses.
    """
    libs = load_libs()
    units = units_per_version()
    paths = set()
    for _, _, names in GROUPS:
        paths |= {p.as_posix() for p, v in collect(libs, units, names) if version in v}
    for lib in libs:
        if lib.get("src_dir") != JSYSTEM_SRC_DIR:
            continue
        for p, v in collect(libs, units, [lib["lib"]]):
            if version in v and str(p).startswith(JSYSTEM_SRC_DIR + "/"):
                paths.add(p.as_posix())
    return sorted(paths)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 if any file would change")
    args = ap.parse_args()

    outputs = build_outputs(load_libs(), units_per_version())

    stale = []
    for path, text in sorted(outputs.items()):
        full = ROOT / path
        if full.exists() and full.read_text(encoding="utf-8") == text:
            continue
        stale.append(path)
        if not args.check:
            full.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path}", file=sys.stderr)
    if args.check and stale:
        print("out of date: " + ", ".join(map(str, stale)), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
